name: 'Upload to blocklet registry'
description: 'Greet someone and record the time'
inputs:
  endpoint:
    description: 'Endpoint of blocklet registry'
    required: true
  access-token:
    description: 'Access token of blocklet registry'
    required: true
  developer-sk:
    description: 'Developer-sk of blocklet registry'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
