name: 'Learn github action'
description: 'Learn github action'
inputs:
  step-1-1:
    description: 'step-1-1'
    required: false
  step-1-2:
    description: 'step-1-2'
    required: false
  step-1-3:
    description: 'step-1-3'
    required: false
  step-1-4:
    description: 'step-1-4'
    required: false

# runs:
#   using: 'node12'
#   main: 'dist/index.js'
runs:
  using: composite
  steps:
    - name: Step-1
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ inputs.step-1-1 || inputs.step-1-2 || inputs.step-1-3 || inputs.step-1-4 }}
    - name: Step-2
      shell: bash
      run: echo "${{ inputs.step-1-1 || inputs.step-1-2 || inputs.step-1-3 || inputs.step-1-4 }}"
