name: 'Upload to blocklet registry'
description: 'Greet someone and record the time'
inputs:
  endpoint:
    description: 'Endpoint of blocklet registry'
    required: false
  access-token:
    description: 'Access token of blocklet registry'
    required: false
  developer-sk:
    description: 'Developer-sk of blocklet registry'
    required: false
  use-exec:
    description: 'is use exec?'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
