name: 'Upload to blocklet registry'
description: 'Greet someone and record the time'
inputs:
  endpoint:
    description: 'Endpoint of blocklet registry'
    required: true
  access-token:
    description: 'Access token of blocklet registry'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node14'
  main: 'dist/index.js'
