on: [push]

jobs:
  Realese:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build
        run: yarn build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*.*'
          token: ${{ secrets.GITHUB_TOKEN }}
