env:
  MAIN_VERSION: 1
on:
  push:
    branches:
      - main

jobs:
  Realese:
    runs-on: ubuntu-latest
    name: Learn github action ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Get npm version
      #   id: package-version
      #   uses: martinbeentjes/npm-get-version-action@master

      # - name: Set yarn cache
      #   uses: c-hive/gha-yarn-cache@v2

      # - name: Install dependencies
      #   run: |
      #     yarn
      #     yarn global add @vercel/ncc

      # - name: Build
      #   run: yarn build

      # - name: Test action
      #   uses: ./
      #   with:
      #     working-directory: ./practice
      #     command: pwd && ls
      # - name: Test action
      #   uses: ./
      #   with:
      #     working-directory: ./dist
      #     command: pwd && ls

      - name: Test action
        uses: ./
        with:
          # step-1-1: 'step-1-1'
          step-1-2: 'step-1-2'
          step-1-3: 'step-1-3'
          step-1-4: 'step-1-4'

      # - name: Config git
      #   run: |
      #     git config --local user.name "LancelotLewis"
      #     git config --local user.email "lancelot_lewis@163.com"

      # - name: Test action-workflow
      #   uses: blocklet/action-workflow@v0.2.1
      #   with:
      #     skip-abtnode: true
      #     skip-release: true

      # - name: Publish dist
      #   run: |
      #     git config --local user.name "LancelotLewis"
      #     git config --local user.email "lancelot_lewis@163.com"
      #     git add dist
      #     git commit --allow-empty -m "Github action build"
      #     git push

      # - name: Realese
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: v${{ steps.package-version.outputs.current-version}}
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Reset tag v${{ env.MAIN_VERSION }}
      #   run: |
      #     git tag -a v${{ env.MAIN_VERSION }} -m 'Sync with v${{ steps.package-version.outputs.current-version}}'
      #     git push origin v${{ env.MAIN_VERSION }} --force
