on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test from self action
        uses: ./
        with:
          registry: 'https://registry.arcblock.io/'
          access-token: '123123'
          developer-sk: '234234'
